name       : ceti2-gtk-theme
version    : 20150923
release    : 1
source     :
    - https://github.com/horst3180/Ceti-2-theme/archive/20150923.tar.gz : a9978f52da7f66f30190183c5f24acb442ef699225e575ea7453682914901525
license    : GPL-3.0
summary    : Vertex Theme
description: |
    Ceti-2 is a theme for GTK 3, GTK 2 and Gnome-Shell. It supports GTK 3 and GTK 2 based desktop environments like Gnome, Unity, Budgie, Pantheon, etc. Ceti-2 is the official continuation of Ceti for Gnome 3.14, 3.16 and 3.18. It has been completely revamped and is now based on Vertex.
setup      : |
     ./autogen.sh $CONFOPTS \
         --disable-cinnamon \
         --enable-gnome-shell \
         --disable-metacity \
         --disable-unity \
         --disable-xfwm \
         --with-gnome=3.18
build      : |
    %make
install    : |
    %make_install
